services:
  - type: web
    name: Docteck-Backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm ci
    startCommand: node index.js
    envVars:
      # Configure these in the Render dashboard or via blueprint sync (do not commit secrets)
      - key: ALLOWED_ORIGINS
        value: https://docteck.vercel.app
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://docteck-backend.onrender.com/api/auth/google/callback
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: no-reply@docteck.local
      - key: NODE_VERSION
        value: "20"
